=== INSPIRE-MIF/daobs/web/src/main/webapp/WEB-INF/xsd/daobsIndicatorConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2014-2016 European Environment Agency

    Licensed under the EUPL, Version 1.1 or â€“ as soon
    they will be approved by the European Commission -
    subsequent versions of the EUPL (the "Licence");
    You may not use this work except in compliance
    with the Licence.
    You may obtain a copy of the Licence at:

    https://joinup.ec.europa.eu/community/eupl/og_page/eupl

    Unless required by applicable law or agreed to in
    writing, software distributed under the Licence is
    distributed on an "AS IS" basis,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    either express or implied.
    See the Licence for the specific language governing
    permissions and limitations under the Licence.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:daobs="http://daobs.org"
           elementFormDefault="qualified" targetNamespace="http://daobs.org">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace"
             schemaLocation="xml.xsd"/>
  <xs:element name="reports">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="daobs:reporting" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="reporting">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="daobs:identification"/>
        <xs:element ref="daobs:variables"/>
        <xs:element ref="daobs:indicators"/>
      </xs:sequence>
      <xs:attribute name="computationTime" type="xs:int"/>
      <xs:attribute name="id" type="xs:NCName"/>
    </xs:complexType>
    <xs:key name="indicator-id-key">
      <xs:selector
        xpath="daobs:variables/daobs:variable|daobs:indicators/daobs:indicator"/>
      <xs:field xpath="@id"/>
    </xs:key>
  </xs:element>
  <xs:element name="identification">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="daobs:title"/>
        <xs:element ref="daobs:author" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="daobs:url" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="title">
    <xs:complexType mixed="true">
      <xs:attribute ref="xml:lang" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="author" type="xs:string"/>
  <xs:element name="url" type="xs:string"/>
  <xs:element name="variables">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="daobs:variable"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="indicators">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="daobs:indicator"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="variable">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="daobs:name"/>
        <xs:element ref="daobs:query" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="daobs:format" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="daobs:value" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="daobs:status" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="daobs:comment" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="default" use="optional" type="xs:double"/>
      <xs:attribute name="numberFormat" use="optional" type="xs:string"/>
      <xs:attribute name="error" use="optional" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="indicator">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="daobs:name"/>
        <xs:element ref="daobs:expression"/>
        <xs:element ref="daobs:parameters"/>
        <xs:element ref="daobs:format" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="daobs:value" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="daobs:status" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="daobs:comment" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="numberFormat" use="optional" type="xs:string"/>
      <xs:attribute name="error" use="optional" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="name">
    <xs:complexType mixed="true">
      <xs:attribute ref="xml:lang" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="value" type="xs:string"/>
  <xs:element name="format" type="xs:string"/>
  <xs:element name="query">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="statsField" use="optional" type="xs:string"/>
          <xs:attribute name="stats" use="optional">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="min"/>
                <xs:enumeration value="max"/>
                <xs:enumeration value="count"/>
                <xs:enumeration value="countDistinct"/>
                <xs:enumeration value="missing"/>
                <xs:enumeration value="mean"/>
                <xs:enumeration value="sum"/>
                <xs:enumeration value="stddev"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="expression" type="xs:string"/>
  <xs:element name="comment" type="xs:string"/>
  <xs:element name="status" type="xs:string"/>
  <xs:element name="parameters">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="daobs:parameter"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="parameter">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="error" use="optional" type="xs:boolean"/>
      <xs:attribute name="status" use="optional" type="xs:string"/>
      <xs:attribute name="value" use="optional" type="xs:string"/>
    </xs:complexType>
    <!--<xs:keyref refer="daobs:indicator-id-key" name="indicator-id-fkey">
      <xs:selector xpath="."></xs:selector>
      <xs:field xpath="@id"></xs:field>
    </xs:keyref>-->
  </xs:element>

</xs:schema>

=== INSPIRE-MIF/daobs/web/src/main/webapp/WEB-INF/datadir/monitoring/config-inspire2019-first-theme-only.xml
<!--

    Copyright 2014-2016 European Environment Agency

    Licensed under the EUPL, Version 1.1 or â€“ as soon
    they will be approved by the European Commission -
    subsequent versions of the EUPL (the "Licence");
    You may not use this work except in compliance
    with the Licence.
    You may obtain a copy of the Licence at:

    https://joinup.ec.europa.eu/community/eupl/og_page/eupl

    Unless required by applicable law or agreed to in
    writing, software distributed under the Licence is
    distributed on an "AS IS" basis,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    either express or implied.
    See the Licence for the specific language governing
    permissions and limitations under the Licence.

-->
<daobs:reporting xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xmlns:daobs="http://daobs.org"
                 xsi:schemaLocation="http://daobs.org ../xsd/daobsIndicatorConfig.xsd"
                 id="inspire">
  <daobs:identification>
    <daobs:title xml:lang="en">Monitoring Indicators (2019) - Beta</daobs:title>
    <daobs:author>Monitoring and Reporting Drafting Team</daobs:author>
    <daobs:url>http://inspire.ec.europa.eu/index.cfm/pageid/5022</daobs:url>
  </daobs:identification>

  <daobs:variables>
    <!-- Indicator MDi1 (Existence of metadata) -->

    <!-- DSv are estimates based on metadata. See MDvXX.
    The reported value may be more than this. -->
    <daobs:variable id="DSv_Num1" numberFormat="#">
      <daobs:name xml:lang="en">Number of spatial data sets for Annex I</daobs:name>
      <daobs:query>+documentType:metadata +(resourceType:dataset resourceType:series) +inspireAnnexForFirstTheme:i</daobs:query>
      <daobs:comment>The value is based on the harvested records. It may be
        underestimated
        if the number of spatial data set does not have metadata or if error
        occurred
        during harvesting.</daobs:comment>
    </daobs:variable>

    <daobs:variable id="DSv_Num2" numberFormat="#">
      <daobs:name xml:lang="en">Number of spatial data sets for Annex II</daobs:name>
      <daobs:query>+documentType:metadata +(resourceType:dataset resourceType:series) +inspireAnnexForFirstTheme:ii</daobs:query>
      <daobs:comment>The value is based on the harvested records. It may be
        underestimated
        if the number of spatial data set does not have metadata or if error
        occurred
        during harvesting.</daobs:comment>
    </daobs:variable>

    <daobs:variable id="DSv_Num3" numberFormat="#">
      <daobs:name xml:lang="en">Number of spatial data sets for Annex III</daobs:name>
      <daobs:query>+documentType:metadata +(resourceType:dataset resourceType:series) +inspireAnnexForFirstTheme:iii</daobs:query>
      <daobs:comment>The value is based on the harvested records. It may be
        underestimated
        if the number of spatial data set does not have metadata or if error
        occurred
        during harvesting.</daobs:comment>
    </daobs:variable>


    <daobs:variable id="SDSv_Num" numberFormat="#">
      <daobs:name xml:lang="en">Number of spatial data services</daobs:name>
      <daobs:query>+documentType:metadata +resourceType:service</daobs:query>
      <!--<daobs:query>+documentType:metadata +resourceType:service +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii)</daobs:query>-->
      <daobs:comment>Only services having an INSPIRE annex are took into
        account. We may harvest records related to no annex.</daobs:comment>
    </daobs:variable>


    <daobs:variable id="NSv_NumDiscServ" numberFormat="#">
      <daobs:name xml:lang="en">Number of discovery services</daobs:name>
      <daobs:query>+documentType:metadata +resourceType:service +inspireServiceType:discovery</daobs:query>
      <!--<daobs:query>+documentType:metadata +resourceType:service +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii) +inspireServiceType:discovery</daobs:query>-->
    </daobs:variable>

    <daobs:variable id="NSv_NumViewServ" numberFormat="#">
      <daobs:name xml:lang="en">Number of view services</daobs:name>
      <daobs:query>+documentType:metadata +resourceType:service +inspireServiceType:view</daobs:query>
      <!--<daobs:query>+documentType:metadata +resourceType:service +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii) +inspireServiceType:view</daobs:query>-->
    </daobs:variable>

    <daobs:variable id="NSv_NumDownlServ" numberFormat="#">
      <daobs:name xml:lang="en">Number of download services</daobs:name>
      <daobs:query>+documentType:metadata +resourceType:service +inspireServiceType:download</daobs:query>
      <!--<daobs:query>+documentType:metadata +resourceType:service +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii) +inspireServiceType:download</daobs:query>-->
    </daobs:variable>

    <daobs:variable id="NSv_NumInvkServ" numberFormat="#">
      <daobs:name xml:lang="en">Number of invoke services</daobs:name>
      <daobs:query>+documentType:metadata +resourceType:service +inspireServiceType:invoke</daobs:query>
      <!--<daobs:query>+documentType:metadata +resourceType:service +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii) +inspireServiceType:invoke</daobs:query>-->
    </daobs:variable>

    <daobs:variable id="NSv_NumTransfServ" numberFormat="#">
      <daobs:name xml:lang="en">Number of transformation services</daobs:name>
      <daobs:query>+documentType:metadata +resourceType:service +inspireServiceType:transformation</daobs:query>
      <!--<daobs:query>+documentType:metadata +resourceType:service +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii) +inspireServiceType:transformation</daobs:query>-->
    </daobs:variable>


    <daobs:variable id="MDv11" numberFormat="#">
      <daobs:name xml:lang="en">Number of spatial data sets for Annex I that
        have metadata</daobs:name>
      <daobs:query>+documentType:metadata +(resourceType:dataset resourceType:series) +inspireAnnexForFirstTheme:i</daobs:query>
    </daobs:variable>

    <daobs:variable id="MDv12" numberFormat="#">
      <daobs:name xml:lang="en">Number of spatial data sets for Annex II that
        have metadata</daobs:name>
      <daobs:query>+documentType:metadata +(resourceType:dataset resourceType:series) +inspireAnnexForFirstTheme:ii</daobs:query>
    </daobs:variable>

    <daobs:variable id="MDv13" numberFormat="#">
      <daobs:name xml:lang="en">Number of spatial data sets for Annex III that
        have metadata</daobs:name>
      <daobs:query>+documentType:metadata +(resourceType:dataset resourceType:series) +inspireAnnexForFirstTheme:iii</daobs:query>
    </daobs:variable>


    <daobs:variable id="MDv14" numberFormat="#">
      <daobs:name xml:lang="en">Number of spatial data services that have
        metadata</daobs:name>
      <daobs:query>+documentType:metadata +resourceType:service</daobs:query>
      <!--<daobs:query>+documentType:metadata +resourceType:service +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii)</daobs:query>-->
    </daobs:variable>


    <!-- Indicator MDi2 (Conformity of metadata) -->
    <daobs:variable id="MDv21" numberFormat="#">
      <daobs:name xml:lang="en">Number of spatial data sets for Annex I that
        have conformant metadata</daobs:name>
      <daobs:query>+documentType:metadata +(resourceType:dataset resourceType:series) +isAboveThreshold:true +inspireAnnexForFirstTheme:i</daobs:query>
      <daobs:comment>INSPIRE validator is used to validate records.</daobs:comment>
    </daobs:variable>

    <daobs:variable id="MDv22" numberFormat="#">
      <daobs:name xml:lang="en">Number of spatial data sets for Annex II that
        have conformant metadata</daobs:name>
      <daobs:query>+documentType:metadata +(resourceType:dataset resourceType:series) +isAboveThreshold:true +inspireAnnexForFirstTheme:ii</daobs:query>
      <daobs:comment>INSPIRE validator is used to validate records.</daobs:comment>
    </daobs:variable>

    <daobs:variable id="MDv23" numberFormat="#">
      <daobs:name xml:lang="en">Number of spatial data sets for Annex III that
        have conformant metadata</daobs:name>
      <daobs:query>+documentType:metadata +(resourceType:dataset resourceType:series) +isAboveThreshold:true +inspireAnnexForFirstTheme:iii</daobs:query>
      <daobs:comment>INSPIRE validator is used to validate records.</daobs:comment>
    </daobs:variable>

    <daobs:variable id="MDv24" numberFormat="#">
      <daobs:name xml:lang="en">Number of spatial data services that have
        conformant metadata</daobs:name>
      <daobs:query>+documentType:metadata +(resourceType:service) +isAboveThreshold:true</daobs:query>
      <!--<daobs:query>+documentType:metadata +(resourceType:service) +isAboveThreshold:true +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii)</daobs:query>-->
      <daobs:comment>INSPIRE validator is used to validate records.</daobs:comment>
    </daobs:variable>


    <!-- INSPIRE DSi1 (Geographical coverage of spatial data sets) -->

    <!-- INSPIRE DSi2 (Conformity of spatial data sets) -->
    <daobs:variable id="DSv21" numberFormat="#">
      <daobs:name xml:lang="en">Number of conformant spatial data sets for Annex
        I that have conformant metadata</daobs:name>
      <daobs:query>+documentType:metadata +(resourceType:dataset resourceType:series) +isAboveThreshold:true +inspireAnnexForFirstTheme:i +inspireConformResource:true</daobs:query>
      <daobs:comment>Check the metadata record using INSPIRE validator and check
        that the Commission Regulation (EU) No 1089/2010 report a conform
        resource.</daobs:comment>
    </daobs:variable>

    <daobs:variable id="DSv22" numberFormat="#">
      <daobs:name xml:lang="en">Number of conformant spatial data sets for Annex
        II that have conformant metadata</daobs:name>
      <daobs:query>+documentType:metadata +(resourceType:dataset resourceType:series) +isAboveThreshold:true +inspireAnnexForFirstTheme:ii +inspireConformResource:true</daobs:query>
